Repository mlr-org/mlr3learners, pull requests merged in 2019-11, with the labels that each got.

#51 Rewrite kknn and fix predict_type bug
  R/LearnerClassifKKNN.R
  R/LearnerRegrKKNN.R
Labels: Priority: High, Type: Bug

#53 Fix predict_type bug in xgboost
  R/LearnerClassifXgboost.R
Labels: Priority: High, Type: Bug

#46 Update parameters and dependencies of all learners
  NEWS.md
  R/LearnerClassifGlmnet.R
  R/LearnerClassifLDA.R
  R/LearnerClassifNaiveBayes.R
  R/LearnerClassifQDA.R
  R/LearnerClassifRanger.R
  R/LearnerClassifSVM.R
  R/LearnerClassifXgboost.R
  R/LearnerRegrGlmnet.R
  R/LearnerRegrKM.R
  R/LearnerRegrRanger.R
  R/LearnerRegrSVM.R
Labels: Status: Completed, Type: Maintenance

#31 Update xgboost learner to latest CRAN version
  NEWS.md
  R/LearnerClassifXgboost.R
  R/LearnerRegrXgboost.R
  man/LearnerClassifXgboost.Rd
Labels: Priority: Medium, Status: Completed, Type: Maintenance
